import { ApiProperty, ApiPropertyOptional } from '@nestjs/swagger';
import {
  IsDateString,
  IsIn,
  IsNumber,
  IsOptional,
  IsString,
  Min,
} from 'class-validator';
import { DealStatus } from '../../../common/constants';

export class CreateDealDto {
  @ApiPropertyOptional({
    example: 'clxxxxxxxxxxxxxx',
    description: 'POSP ID — omit or null for Self-issued by manager',
  })
  @IsString()
  @IsOptional()
  pospId?: string;

  @ApiPropertyOptional({
    example: 'clxxxxxxxxxxxxxx',
    description:
      'Existing Customer ID from search — links the deal to a Customer record',
  })
  @IsString()
  @IsOptional()
  customerId?: string;

  @ApiProperty({ example: 'Rajesh Mehta' })
  @IsString()
  customer: string;

  @ApiProperty({ example: 'Life' })
  @IsString()
  policy: string;

  @ApiProperty({ example: 5000000 })
  @IsNumber()
  @Min(0)
  sum: number;

  @ApiProperty({ example: 45000 })
  @IsNumber()
  @Min(0)
  premium: number;

  @ApiPropertyOptional({
    example: 6000,
    description:
      'COA — raw value (interpret with coaType). SUPER_ADMIN only; ignored from other roles.',
  })
  @IsNumber()
  @Min(0)
  @IsOptional()
  coa?: number;

  @ApiPropertyOptional({
    enum: ['PERCENT', 'AMOUNT'],
    example: 'AMOUNT',
    description: 'COA entry mode',
  })
  @IsIn(['PERCENT', 'AMOUNT'])
  @IsOptional()
  coaType?: string;

  @ApiPropertyOptional({
    example: 3000,
    description:
      'Retained margin (₹). SUPER_ADMIN only; ignored from other roles.',
  })
  @IsNumber()
  @Min(0)
  @IsOptional()
  margin?: number;

  @ApiProperty({ enum: ['H', 'W', 'C', 'D'], example: 'W' })
  @IsIn(Object.values(DealStatus))
  status: DealStatus;

  @ApiProperty({ example: '2026-06-15' })
  @IsDateString()
  expected: string;

  @ApiPropertyOptional({
    example: 'PRP-2026-123456',
    description: 'Proposal number — auto-generated by server if not supplied',
  })
  @IsString()
  @IsOptional()
  proposal?: string;

  @ApiPropertyOptional({
    example: 'POL-2026-987654',
    description: 'Policy number — set only after insurer issues the policy',
  })
  @IsString()
  @IsOptional()
  policyNo?: string;

  @ApiPropertyOptional({
    example: '2026-05-15',
    description: 'Policy issuance date — set only when policy is issued',
  })
  @IsDateString()
  @IsOptional()
  issued?: string;

  @ApiPropertyOptional({ example: 'Awaiting medical' })
  @IsString()
  @IsOptional()
  remarks?: string;

  // ── Geo fields — populated server-side from POSP or SalesTeam, never from client ──
  @IsString()
  @IsOptional()
  zoneId?: string;

  @IsString()
  @IsOptional()
  regionId?: string;

  @IsString()
  @IsOptional()
  areaId?: string;

  @IsString()
  @IsOptional()
  districtId?: string;
}
