apiVersion: 1

datasources:
  - name: Loki
    type: loki
    uid: roinet-loki
    access: proxy
    url: http://loki:3100
    isDefault: true
    jsonData:
      maxLines: 2000
      derivedFields:
        - datasourceUid: roinet-loki
          matcherRegex: '"userId":"([^"]+)"'
          name: userId
          url: ''
        - datasourceUid: roinet-loki
          matcherRegex: '"path":"([^"]+)"'
          name: path
          url: ''
